preciocompu= float(input("Ingrese el valor del computador pago de contado:"))
valorcuotas= float (input("Ingrese el valor de las cuotas en caso de pagarlo a 12 cuotas:"))
pagofinalintereses=(valorcuotas*12)
print("Se pagaría:", str(pagofinalintereses), "por el computador")
cuotasininteres=(preciocompu/12)
print("El valor de cada cuota sin nungun interes sería de:", str(cuotasininteres))
diferencia=(valorcuotas-cuotasininteres)
porcentaje=((diferencia*100)/preciocompu)
print("El porcentaje de intereses por cuota es de:",str(porcentaje), "%")