chelinesaustriacos= float (input ("Ingrese la cantidad en chelines austriacos:"))
chelin = (956871/100)
total1=(chelin*chelinesaustriacos)
print("Esto es equivalente a:", str(total1), "pesetas.")
dracmasgriegos= float (input("Ingrese la cantidad en Dracmas Griegos:"))
dracma=(88607/100)
francofrances=(20110)
total2=((dracmasgriegos*dracma)/francofrances)
print("Esto equivale a", str(total2), "francos franceses.")
pesetas= float (input("Ingrese la cantidad en pesetas:"))
dolares=(pesetas/122499)
liras=(pesetas/928.9)
print("Esto equivale a", str(dolares), "dolares.")
print("Esto equivale a", str(liras), "liras.")