trabajo1=float (input("Digite la nota de su primer trabajo: "))
trabajo2=float (input("Digite la nota de su segundo trabajo: "))
trabajo3=float (input("Digite la nota de su tercer trabajo: "))
ExamenFinal=float (input("Digite la nota de su parcial final: "))
trabajoFinal=float (input("Digite la nota de su trabajo final: "))
notatrabajos=(((trabajo1+trabajo2+trabajo3)/3)*0.55)
notaexamen= (ExamenFinal*0.30)
notatrabajofinal= (trabajoFinal*0.15)
NotaFinal= (notatrabajos+notaexamen+notatrabajofinal)
print("Su nota final es de:", str(NotaFinal))