ExamenMatematica= float(input("Ingrese la nota del examen de matemáticas:"))
tarea1Matematica= float(input("Ingrese la nota de la tarea #1 de matemáticas:"))
tarea2Matematica= float(input("Ingrese la nota de la tarea #2 de matemáticas:"))
tarea3Matematica= float(input("Ingrese la nota de la tarea #3 de matemáticas:"))
notaExMate=(ExamenMatematica*0.9)
notatareasMate=(((tarea1Matematica+tarea2Matematica+tarea3Matematica)/3)*0.1)
promedioMate=(notaExMate+notatareasMate)
print("El promedio en Matematicas es de:", str(promedioMate))
ExamenFisica= float(input("Ingrese la nota del examen de física:"))
tarea1Fisica= float(input("Ingrese la nota de la tarea #1 de física:"))
tarea2Fisica= float(input("Ingrese la nota de la tarea #2 de física:"))
notaExFisi=(ExamenFisica*0.8)
notatareasfisi=(((tarea1Fisica+tarea2Fisica)/2)*0.2)
promedioFisica=(notaExFisi+notatareasfisi)
print("El promedio en Física es de:", str(promedioFisica))
ExamenQuímica= float(input("Ingrese la nota del examen de química:"))
tarea1Quimica= float(input("Ingrese la nota de la tarea #1 de química:"))
tarea2Quimica= float(input("Ingrese la nota de la tarea #2 de química:"))
tarea3Quimica= float(input("Ingrese la nota de la tarea #3 de química:"))
notaExQuimi=(ExamenQuímica*0.85)
notatareasquimi=(((tarea1Quimica+tarea2Quimica+tarea3Quimica)/3)*0.15)
promedioquimi=(notaExQuimi+notatareasquimi)
print("El promedio en química es de:", str(promedioquimi))