sueldobase= float(input("Digite su sueldo base: "))
venta1= float (input("Digite el valor de la venta #1:"))
venta2= float (input("Digite el valor de la venta #2:"))
venta3= float (input("Digite el valor de la venta #3:"))
totalventas=(venta1+venta2+venta3)
comision= (totalventas*0.10)
totalsueldo= (sueldobase+comision)
print("El valor de la comisión fue de:", str(comision))
print ("El salario final es de:", str(totalsueldo))